### ISSUE TITLE
 Property 'cut' does not exist on type 

### ISSUE THREAD

**Issue by veluvj** [willmendesneto/ngx-copy-to-clipboard#8]
I had been a day long debugging this error but no solution found 

```
error TS2339: Property 'cut' does not exist on type 'PrivacyPolicyComponent'.
    
    46         [action]="cut"
                         ~~~
    
```    
and Copy text  was not shown as  button.

  ```
 <ngx-copy-to-clipboard
        target="#text-content"
        [action]="cut"
        [success]="onSuccess"
        [error]="onError"
        >Copy</ngx-copy-to-clipboard>
 
 
<div #text-content>
    <p>Hello!</p>
</div>

```  

what's wronng in my code ?

**Comment by willmendesneto** [comment]
Hi @veluvj , thanks for raising this issue.

I'm taking a look and I'll reply in this issue as soon as I find something useful.

**Comment by willmendesneto** [comment]
@veluvj This error is happening because there's no element with id `text-content`. Target is related to a DOM element with the id. However, the way you added was based on ng-template reference, which is not used in this module.

The correct syntax for your example is 

```
<ngx-copy-to-clipboard
      target="#text-content"
      [action]="cut"
      [success]="onSuccess"
      [error]="onError"
      >Copy</ngx-copy-to-clipboard>


<div id="text-content">
  <p>Hello!</p>
</div>
```

You also can check how it works by changing the default demo sample for this module available in https://stackblitz.com/edit/ngx-copy-to-clipboard-sample?file=app%2Fapp.component.html

**Comment by willmendesneto** [comment]
With that, I'm closing this issue. Feel free to reopen it again and add a link for a [stackblitz demo](https://stackblitz.com/edit/ngx-copy-to-clipboard-sample?file=app%2Fapp.component.html) simulating the issue if you feel that didn't solve.

One more time, thank you so much @veluvj for raising that up!
